ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.eigen_stake_drain]
path = "out/EigenStakeDrainTrap.sol/EigenStakeDrainTrap.json"
response_contract = "0x0711dac167e5c9bdbbc147192949d139a30d80b8"
# Updated response signature (includes thresholdBps)
response_function = "respondToStakeDrain(address,uint256,uint256,uint256,uint256)"
cooldown_period_blocks = 30
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = ["YOUR_OPERATOR_ADDRESS"]
